apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  type: NodePort
  selector:
    tier: backend
  clusterIP: 10.152.183.199
  externalTrafficPolicy: Cluster
  ports:
  - name: myport
    port: 3000
    protocol: TCP
    targetPort: 3000
  type: LoadBalancer
